title: Rewind That Font
description: Rewind That Font, a blog, taking a look back at the most
  unforgettable and iconic typography throughout the history of film.
header_text: "Rewind That Font, looking at the past and present of film typography. "
footer_text: Copyright 2020 Rewind That Font
header_feature_image: ../uploads/the-end-neon-sign-vintage-movie-ending-neon-frame-vector-22727687.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
