title: Rewind That Font
description: A blog taking a look back at the most unforgettable and iconic
  typography throughout the timeline of film.
header_text: "The past and present of film typography. "
footer_text: Copyright 2020 Rewind That Font
header_feature_image: ../uploads/film-career.png
bannerheight: 40vmax
logo: ../uploads/rewind-that-font.png
favicon: ../uploads/copy-of-rewind-that-font.png
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: "Exist "
    siteurl: https://existnewsmedia.wordpress.com
    tab: true
  - name: About Me
    tab: true
    siteurl: /aboutme
