title: Rewind That Font
description: A blog taking a look back at the most unforgettable and iconic
  typography throughout the timeline of film.
header_text: "The past and present of film typography. "
footer_text: Copyright 2020 Rewind That Font
header_feature_image: ../uploads/film-career.png
bannerheight: 50vmax
logo: ../uploads/ec07f973-6231-472e-9621-0678c778ce5e_4_5005_c.jpeg
favicon: ../uploads/ec07f973-6231-472e-9621-0678c778ce5e_4_5005_c.jpeg
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: "Exist "
    siteurl: https://existnewsmedia.wordpress.com
    tab: true
